# Generated by Django 3.1.1 on 2020-09-15 05:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skn_professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_recommender', models.CharField(choices=[('Professor', 'Professor'), ('Dr', 'Dr'), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Other', 'Other')], max_length=10)),
                ('recommender_first_name', models.CharField(max_length=45)),
                ('recommender_last_name', models.CharField(max_length=45)),
                ('recommender_email', models.EmailField(max_length=150)),
                ('recommender_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('let_professional_know', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('title_of_professional', models.CharField(choices=[('Professor', 'Professor'), ('Dr', 'Dr'), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Other', 'Other')], max_length=10)),
                ('professional_full_name', models.CharField(max_length=150)),
                ('professional_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('professional_email', models.EmailField(max_length=150)),
                ('professional_expertise', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Professional', 'Professional'), ('Partner', 'Partner'), ('Requesting Agency', 'Requesting Agency')], default='Professional', max_length=20),
        ),
        migrations.CreateModel(
            name='RequesterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_full_name', models.CharField(max_length=150)),
                ('requester_organization', models.CharField(max_length=60)),
                ('requester_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('requester_website', models.CharField(max_length=60)),
                ('requester_photo_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('referee_one_full_name', models.CharField(blank=True, max_length=60, null=True)),
                ('referee_one_phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('referee_one_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('referee_one_social_media_handle', models.CharField(blank=True, max_length=150, null=True)),
                ('referee_one_workplace', models.CharField(blank=True, max_length=60, null=True)),
                ('referee_two_full_name', models.CharField(blank=True, max_length=60, null=True)),
                ('referee_two_phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('referee_two_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('referee_two_social_media_handle', models.CharField(blank=True, max_length=150, null=True)),
                ('referee_two_workplace', models.CharField(blank=True, max_length=60, null=True)),
                ('admin_approved', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('region_of_residence', models.CharField(max_length=150)),
                ('town_or_city_of_residence', models.CharField(max_length=150)),
                ('field_of_expertise', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Business/Commerce & Industry', 'Business/Commerce & Industry'), ('Communications, Media, IT', 'Communications, Media, IT'), ('Criminology & Criminal Justice', 'Criminology & Criminal Justice'), ('Culture & Heritage', 'Culture & Heritage'), ('Development and International Development', 'Development and International Development'), ('Diplomacy and International Relations', 'Diplomacy and International Relations'), ('Economy', 'Economy'), ('Education', 'Education'), ('Elections', 'Elections'), ('Energy', 'Energy'), ('Employment', 'Employment'), ('Finance, Banking, Microfinance', 'Finance, Banking, Microfinance'), ('Fiscal Policy', 'Fiscal Policy'), ('Government & Politics', 'Government & Politics'), ('Health', 'Health'), ('History of Ghana', 'History of Ghana'), ('Humanities', 'Humanities'), ('Infrastructure & Planning', 'Infrastructure & Planning'), ('Law/Legal', 'Law/Legal'), ('Linguistics/Language', 'Linguistics/Language'), ('Public Service & Public Administration', 'Public Service & Public Administration'), ('Security & Defense', 'Security & Defense'), ('Social Sciences', 'Social Sciences'), ('Science & STEM', 'Science & STEM'), ('Social Justice, Gender, Youth & Diversity', 'Social Justice, Gender, Youth & Diversity'), ('Sports', 'Sports'), ('Violence Against Women', 'Violence Against Women'), ('Women and Politics', 'Women and Politics'), ('Women in Media', 'Women in Media'), ('Other', 'Other')], max_length=60)),
                ('other_field_of_expertise_name', models.CharField(blank=True, max_length=150)),
                ('specialties_under_expertise', models.CharField(max_length=150)),
                ('level_of_expertise', models.CharField(choices=[('Early Career: 3-6 Years', 'Early Career: 3-6 Years'), ('Mid Career: 7-12 Years', 'Mid Career: 7-12 Years'), ('Experienced: 12+ Years', 'Experienced: 12+ Years')], max_length=30)),
                ('job_title', models.CharField(max_length=60)),
                ('job_description', models.CharField(max_length=300)),
                ('institution', models.CharField(max_length=150)),
                ('link_to_social_media_handle', models.CharField(blank=True, max_length=150, null=True)),
                ('languages_spoken', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=300)),
                ('certify_account', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('cv_resume', models.FileField(upload_to='')),
                ('assistant_name', models.CharField(blank=True, max_length=45, null=True)),
                ('assistant_phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('assistant_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('referee_one_full_name', models.CharField(max_length=60)),
                ('referee_one_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('referee_one_email', models.EmailField(max_length=150)),
                ('referee_one_workplace', models.CharField(max_length=60)),
                ('referee_two_full_name', models.CharField(max_length=60)),
                ('referee_two_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('referee_two_email', models.EmailField(max_length=150)),
                ('referee_two_workplace', models.CharField(max_length=60)),
                ('how_did_you_discover_skn', models.CharField(choices=[('Friends & Family', 'Friends & Family'), ('Social Media', 'Social Media'), ('Publications', 'Publications'), ('TV', 'TV'), ('Radio', 'Radio'), ('Other', 'Other')], default='Other', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('terms_and_conditions_confirmed', models.BooleanField()),
                ('admin_approved', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
