# Generated by Django 3.1.1 on 2020-09-10 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skn_professionals', '0004_auto_20200910_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesterprofile',
            name='referee_two_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
