# Generated by Django 3.1.1 on 2020-09-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skn_professionals', '0005_auto_20200910_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesterprofile',
            name='admin_approved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='level_of_expertise',
            field=models.CharField(choices=[('Early Career: 3-6 Years', 'Early Career: 3-6 Years'), ('Mid Career: 7-12 Years', 'Mid Career: 7-12 Years'), ('Experienced: 12+ Years', 'Experienced: 12+ Years')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Professional', 'Professional'), ('Partner', 'Partner'), ('Requesting Agency', 'Requesting Agency')], default='Professional', max_length=20),
        ),
    ]
